/* tslint:disable */
/* eslint-disable */
/**
 * Pilot Mobile App API
 * API to support retreiving config data, submit app paradata and obtain graphs to be used by the WellBeringCheck mobile app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Style of a given graph type. This allows to try options if needed
 * @export
 * @enum {string}
 */
export enum GraphStyle {
    Line = 'line',
    Pie = 'pie',
    Table = 'table'
}

export function GraphStyleFromJSON(json: any): GraphStyle {
    return GraphStyleFromJSONTyped(json, false);
}

export function GraphStyleFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphStyle {
    return json as GraphStyle;
}

export function GraphStyleToJSON(value?: GraphStyle | null): any {
    return value as any;
}

