/* tslint:disable */
/* eslint-disable */
/**
 * Pilot Mobile App API
 * API to support retreiving config data, submit app paradata and obtain graphs to be used by the WellBeringCheck mobile app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetPasswordInput
 */
export interface SetPasswordInput {
    /**
     * Salt used to hash the password
     * @type {string}
     * @memberof SetPasswordInput
     */
    salt: string;
    /**
     * Hashed password
     * @type {string}
     * @memberof SetPasswordInput
     */
    passwordHash: string;
    /**
     * Id of the security question chosen by respondent
     * @type {number}
     * @memberof SetPasswordInput
     */
    securityQuestionId: number;
    /**
     * Salt used to hash the security question answer
     * @type {string}
     * @memberof SetPasswordInput
     */
    securityAnswerSalt?: string;
    /**
     * Hashed security question
     * @type {string}
     * @memberof SetPasswordInput
     */
    securityAnswerHash?: string;
}

export function SetPasswordInputFromJSON(json: any): SetPasswordInput {
    return SetPasswordInputFromJSONTyped(json, false);
}

export function SetPasswordInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetPasswordInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'salt': json['salt'],
        'passwordHash': json['passwordHash'],
        'securityQuestionId': json['securityQuestionId'],
        'securityAnswerSalt': !exists(json, 'securityAnswerSalt') ? undefined : json['securityAnswerSalt'],
        'securityAnswerHash': !exists(json, 'securityAnswerHash') ? undefined : json['securityAnswerHash'],
    };
}

export function SetPasswordInputToJSON(value?: SetPasswordInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'salt': value.salt,
        'passwordHash': value.passwordHash,
        'securityQuestionId': value.securityQuestionId,
        'securityAnswerSalt': value.securityAnswerSalt,
        'securityAnswerHash': value.securityAnswerHash,
    };
}


