export const resources = {
    culture: 'en',
    getString: function (key) {
        return this.data[this.culture][key];
    },
    data: {
        en: {
            //global
            "gl.next": "Next",
            "gl.decline": "Decline",
            "gl.agree": "Agree",
            "gl.return": "Return",
            //getting started
            "getting_started": "Getting Started",
            "getting_started_content": "Why we are conducting this study? The purpose of this study is to better understand the everyday well-being of Canadians by asking about activities and feelings as they are happening. To do this, participants will download an app on their smartphones and answer a few questions at different intervals throughout the day, over a short period of time. The results will help us to find connections between activities and well-being, and be used to develop programs that enhance people’s lives. In the future, an app could be used as a faster and more convenient way to complete other Statistics Canada surveys. Information may also be used by Statistics Canada for other statistical and research purposes. Although voluntary, your participation is important so that the information collected is as accurate and complete as possible. Authorization and confidentiality Data are collected under the authority of the Statistics Act, Revised Statutes of Canada, 1985, Chapter S-19. Your information will be kept strictly confidential. Record linkages To enhance the data from this survey and to reduce the reporting burden, Statistics Canada may combine the information you provide with other survey or administrative data sources. Time required to complete this questionnaire This questionnaire will take about 2 minutes to complete. Please note that you will not be able to change any information you reported once you have submitted the questionnaire. To navigate the questionnaire Use the Previous and Next buttons located at the bottom right of each page. Session timeout After 2 hours of inactivity, your session will time out. You will not be able to access any unsaved information. After 15 minutes of inactivity, Well-Being Check will lock. You will need to enter your password to continue. Definitions and explanations A help button is available for certain questions. Press this button for additional information or clarification.",
            //terms & conditions
            "terms_and_conditions": "Terms and conditions",
            "terms_and_conditions_content": "The following Terms and Conditions arise from Statistics Canada's character as a public institution that must operate transparently and in conformity with the provisions of federal legislation Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            //Register screen
            "reg.pass.validation.empty": "Password cannot be empty.",
            "reg.pass.validation.min_eight": "Password must be at least 8 characters",
            "reg.pass.validation.upper": "Password must containt at least 1 upper case",
            "reg.pass.validation.special": "Password must containt at least 1 special character",
            "reg.pass.validation.lower": "Password must containt at least 1 lower case",
            "reg.pass.validation.number": "Password must containt at least 1 number",
            "reg.ques.select": "Select question",
            "reg.ques.mother": "What is your mother’s maiden name?",
            "reg.ques.school": "What primary school did you go to?",
            "reg.ques.car": "What was your first car?",
            "reg.ques.sport": "What is your favourite game or sport?",
            "reg.ques.job": "What was your first job?",
            //about
            "about_title": "Why are we conducting this study?",
            "about_content": "The purpose of this study is to better Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
            "about_title_two": "Authorization and confidentiality",
            "about_content_two": "Data are collected under the authority Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
            "create_password": "Create Password",
            "password": "Password",
            "confirm_password": "Confirm Password",
            "the_answer_is:": "The answer is:",
            "btn_create": "Create",
            "login": "Login",
            "start_survey": "Start Your Survey",
            "settings": "Settings",
            "result": "Result",
            "about_the_survey": "About the Survey",
            "term_and_condition": "Term & Condition",
            "contact_us": "Contact us",
            "warning": "Warning",
            "match_password_error": "You must provide matched password and secrity question and answer !",
            "ok": "Ok",
            "term_and condition_content": "When you continue use this app, that means you automatically agree on this Term and condition.",

            "Your feeling this week":"Your feeling this week",
             "Your feelings":"Your feelings",
             "Detail":"Detail",
             "Summary":"Summary",
              "How you are feeling by location": "How you are feeling by location",
              "How you are feeling with others":"How you are feeling with others",
              "How you are feeling by activity":"How you are feeling by activity",
              "How you are feeling by location help":"This is your feeling by location",
              "How you are feeling with others help":"This is your feeling with others",
              "How you are feeling by activity help":"This is your feeling by activity",
              "Your feeling help":"This is your feelings",

            "notifications": "Notifications",
            "wake_time": "Wake-up time",
            "sleep_time": "Bedtime",
            "number_notifications": "Number of Notifications",
            "language": "Language:",
            "about": "Information",
            "ThankYouA":"Thank you for completing this survey!",
            "ThankYouB":"Thank you for completing this survey! You can review your Well-being Check in the Results menu.",

        },
        fr: {
            //global
            "gl.next": "FR_Next",
            "gl.decline": "FR_Decline",
            "gl.agree": "FR_Agree",
            "gl.return": "Retour",
            //getting started
            "getting_started": "FR_Getting Started",
            "getting_started_content": "FR_Why are we conducting this study? What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            //terms & conditions
            "terms_and_conditions": "FR_Terms and conditions",
            "terms_and_conditions_content": "FR_The following Terms and Conditions arise from Statistics Canada's character as a public institution that must operate transparently and in conformity with the provisions of federal legislation Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            //Register screen
            "reg.pass.validation.empty": "FR_Password cannot be empty.",
            "reg.pass.validation.min_eight": "FR_Password must be at least 8 characters",
            "reg.pass.validation.upper": "FR_Password must containt at least 1 upper case",
            "reg.pass.validation.special": "FR_Password must containt at least 1 special character",
            "reg.pass.validation.lower": "FR_Password must containt at least 1 lower case",
            "reg.pass.validation.number": "FR_Password must containt at least 1 number",
            "reg.ques.select": "FR_Select question",
            "reg.ques.mother": "Quel est le nom de jeune fille de votre mère?",
            "reg.ques.school": "Quel était le nom de votre école primaire?",
            "reg.ques.car": "Quelle a été votre première voiture?",
            "reg.ques.sport": "Quel est votre jeu ou sport préféré?",
            "reg.ques.job": "Quel a été votre premier emploi?",
            //about
            "about_title": "FR_Why are we conducting this study?",
            "about_content": "FR_The purpose of this study is to better Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
            "about_title_two": "FR_Authorization and confidentiality",
            "about_content_two": "FR_Data are collected under the authority Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
            "create_password": "Créer un mot de passe",
            "password": "Mot de passe",
            "confirm_password": "Confirmez le mot de passe",
            "the_answer_is:": "La réponse est:",
            "btn_create": "Créer",
            "login": "S'identifier",
            "start_survey": "Commencer l'enquête",
            "settings": "Paramètres",
            "result": "Résultat",
            "about_the_survey": "A propos de l'enquête",
            "term_and_condition": "Terme et condition",
            "contact_us": "Contactez nous",
            "warning": "Attention",
            "match_password_error": "Vous devez fournir un mot de passe, une question de sécurité et une réponse correspondants!",
            "ok": "D'accord",
            "term_and condition_content": "Lorsque vous continuez à utiliser cette application, cela signifie que vous acceptez automatiquement ces conditions générales.",

            "Your feeling this week":"Votre ressenti cette semaine",
            "Your feelings":"Tes sentiments",
            "Detail":"Détail",
            "Summary":"Sommaire",
            "How you are feeling by location":"Comment vous vous sentez par emplacement",
            "How you are feeling with others":"Comment vous vous sentez avec les autres",
            "How you are feeling by activity":"Comment vous vous sentez par activité",
            "How you are feeling by location help":"C'est votre sentiment par emplacement",
            "How you are feeling with others help":"C'est votre sentiment avec les autres",
            "How you are feeling by activity help":"C'est votre sentiment par activité",
            "Your feeling help":"Ce sont tes sentiments",

            "notifications": "Notifications",
            "wake_time": "Heure du lever",
            "sleep_time": "Heure du coucher",
            "number_notifications" : "Nombre de Notifications",
            "language": "Langue:",
            "about": "Information",
            "ThankYouA":"Nous vous remercions d’avoir participé à l’enquête!",
            "ThankYouB":"Nous vous remercions d’avoir participé à l’enquête! Vous pouvez consulter votre Bilan bien-être dans le menu Résultats.",
        }

    }
};